# Generated by Django 3.2.6 on 2022-10-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('level', models.CharField(choices=[('1', 'Первый уровень'), ('2', 'Второй уровень'), ('3', 'Третий уровень'), ('4', 'Четвертый уровень'), ('5', 'Пятый уровень')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=155)),
                ('employment_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.department')),
            ],
        ),
    ]
